In [1]:
import wikipediaapi
import pandas as pd

In [4]:
df = pd.read_csv("../data/wiki_results.csv")

In [5]:
df.head()

,personLabel,genderLabel,article
0,Andre Geim,männlich,https://de.wikipedia.org/wiki/Andre_Geim
1,Bruce Beutler,männlich,https://de.wikipedia.org/wiki/Bruce_Beutler
2,Manfred Füllsack,männlich,https://de.wikipedia.org/wiki/Manfred_F%C3%BCl...
3,Paul Molitor,männlich,https://de.wikipedia.org/wiki/Paul_Molitor_(In...
4,Benjamin List,männlich,https://de.wikipedia.org/wiki/Benjamin_List

In [8]:
df.groupby('genderLabel').value_counts(normalize=True)

genderLabel  personLabel               article                                                 title
männlich     Erle C. Ellis             https://de.wikipedia.org/wiki/Erle_C._Ellis             Erle C. Ellis               0.003945
             Hauke Bartels             https://de.wikipedia.org/wiki/Hauke_Bartels             Hauke Bartels               0.003945
             Peter Valent              https://de.wikipedia.org/wiki/Peter_Valent              Peter Valent                0.003945
             Christian von Zimmermann  https://de.wikipedia.org/wiki/Christian_von_Zimmermann  Christian von Zimmermann    0.003945
             Christoph Gerhard         https://de.wikipedia.org/wiki/Christoph_Gerhard         Christoph Gerhard           0.003945
                                                                                                                             ...
weiblich     Gitanjali Rao             https://de.wikipedia.org/wiki/Gitanjali_Rao             Gitanjali Rao               0.003584
             Camilla Stoltenberg       https://de.wikipedia.org/wiki/Camilla_Stoltenberg       Camilla Stoltenberg         0.003584
             Bogaletch Gebre           https://de.wikipedia.org/wiki/Bogaletch_Gebre           Bogaletch Gebre             0.003584
             Reinette Biggs            https://de.wikipedia.org/wiki/Reinette_Biggs            Reinette Biggs              0.003584
             Semia Gharbi              https://de.wikipedia.org/wiki/Semia_Gharbi              Semia Gharbi                0.003584
Name: proportion, Length: 771, dtype: float64

In [6]:
df["title"] = df["article"].str.split("/").str[-1]
df["title"] = df["title"].str.replace("_", " ")

In [7]:
df.head()

,personLabel,genderLabel,article,title
0,Andre Geim,männlich,https://de.wikipedia.org/wiki/Andre_Geim,Andre Geim
1,Bruce Beutler,männlich,https://de.wikipedia.org/wiki/Bruce_Beutler,Bruce Beutler
2,Manfred Füllsack,männlich,https://de.wikipedia.org/wiki/Manfred_F%C3%BCl...,Manfred F%C3%BCllsack
3,Paul Molitor,männlich,https://de.wikipedia.org/wiki/Paul_Molitor_(In...,Paul Molitor (Informatiker)
4,Benjamin List,männlich,https://de.wikipedia.org/wiki/Benjamin_List,Benjamin List

In [ ]:
wiki = wikipediaapi.Wikipedia(
    language='de',
    user_agent='research-project'
)

data = []

for title in titles:
    page = wiki.page(title)

    if page.exists():
        data.append({
            "title": title,
            "text": page.text
        })

df = pd.DataFrame(data)

print(df["text"][0][:1000])